[package]
name = "hello-ipl3font"
version = "0.1.0"
authors = ["Jay Oster <jay@kodewerx.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
n64lib = { path = "../n64lib" }
rrt0 = "0.1"
